apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: otu-demo-vm
  namespace: default
  annotations:
    template-version.harvesterhci.io/customName: VUwKPHiE5J
  labels:
    harvesterhci.io/os: linux
    template.harvesterhci.io/templateID: dsc-sles-instance
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '["default/otu-ssh-key"]'
      labels:
        harvesterhci.io/vmName: otu-demo-vm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network.harvesterhci.io/dsc-ntwk-1
                    operator: In
                    values:
                      - 'true'
      architecture: amd64
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 4Gi
      evictionStrategy: LiveMigrateIfPossible
      networks:
        - multus:
            networkName: harvester-public/vlan2229
          name: default
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: otu-demo-vm-disk-0
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              runcmd:
                - sed -i 's|^NETCONFIG_DNS_STATIC_SEARCHLIST.*|NETCONFIG_DNS_STATIC_SEARCHLIST="dsc.prg2.suse.org"|' /etc/sysconfig/network/config
                - sed -i 's|^NETCONFIG_DNS_STATIC_SERVERS=.*|NETCONFIG_DNS_STATIC_SERVERS="10.144.109.8 1.1.1.1"|' /etc/sysconfig/network/config
                - netconfig update -f
                - zypper refresh
                - zypper install -y qemu-guest-agent
                - systemctl enable --now qemu-guest-agent.service
            networkData: |
              version: 2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otu-demo-vm-disk-0
  namespace: default
  annotations:
    harvesterhci.io/imageId: "harvester-public/image-6rv2r"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Block
  storageClassName: longhorn-image-6rv2r