apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: otu-demo-vm
  namespace: default
  annotations:
    # Generates the target 10Gi block storage from the specified Longhorn base image
    harvesterhci.io/volumeClaimTemplates: >-
      [{"metadata":{"name":"otu-demo-vm-disk-0"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-6rv2r"}}]
  labels:
    harvesterhci.io/os: linux
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        # Maps the Harvester KeyPair reference
        harvesterhci.io/sshNames: '["otu-ssh-key"]'
      labels:
        harvesterhci.io/vmName: otu-demo-vm
    spec:
      affinity: {}
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
          requests:
              cpu: 250m
              memory: 4Gi
      evictionStrategy: LiveMigrateIfPossible
      networks:
        - multus:
            networkName: harvester-public/vlan2229
          name: default
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            # Matches the volume claim template defined in metadata annotations
            claimName: otu-demo-vm-disk-0
        - name: cloudinitdisk
          cloudInitNoCloud:
            # Directly provision cloud-config to map the existing sles user with the ssh key
            userData: |
              #cloud-config
              package_update: true
              packages:
                - qemu-guest-agent
              runcmd:
                - systemctl enable --now qemu-guest-agent.service
                - sed -i 's|^NETCONFIG_DNS_STATIC_SEARCHLIST.*|NETCONFIG_DNS_STATIC_SEARCHLIST="dsc.prg2.suse.org"|' /etc/sysconfig/network/config
                - sed -i 's|^NETCONFIG_DNS_STATIC_SERVERS=.*|NETCONFIG_DNS_STATIC_SERVERS="10.144.109.8 1.1.1.1"|' /etc/sysconfig/network/config
                - netconfig update -f