apiVersion: v1
kind: Secret
metadata:
  name: otu-demo-vm-cloudinit
  namespace: default
type: Opaque
stringData:
  # Add your SLES instance configurations/credentials here
  userData: |
    #cloud-config
    password: linux
    chpasswd: { expire: False }
    ssh_pwauth: True
  networkData: |
    version: 2